### ISSUE TITLE
Link name to contact, please

### ISSUE THREAD

**Issue by blausand** [SufficientlySecure/birthday-calendar#97]
I find the age underlined and creating an active link as a two digit phone number, which apparently doesn't make any sense.
Instead, i'd appreciate a lot if the name was linked to the contact so i can easily call and wish a happy birthday.

**Comment by dschuermann** [comment]
Linking from the event title to the contacts is not possible on Android because this requires changing the calendar app that displays the events. The underlining is also done by your calendar app, we cannot change this behaviour.
If you use Google's calendar app there should be a button inside the event that goes to the contact.
